"""
=============================================================================
SENTINELS OF INTEGRITY — AI Origin Detection Route
POST /api/v1/ai-origin — Upload media to detect which AI tool generated it.
=============================================================================

This endpoint accepts direct multipart file uploads (unlike /detect which
takes a URL). It returns immediate attribution results identifying whether
the media was created by ChatGPT/DALL-E, Gemini, Midjourney, Stable
Diffusion, or another AI generative tool.
=============================================================================
"""

import logging
from typing import Optional

from fastapi import APIRouter, HTTPException, UploadFile, File, Form, Query
from app.models.schemas import AIOriginResult
from app.services.ai_origin_service import AIOriginService

logger = logging.getLogger("sentinels.api.ai_origin")

router = APIRouter()

# Maximum allowed file size: 50 MB
MAX_FILE_SIZE = 50 * 1024 * 1024  # 50 MB


@router.post(
    "/ai-origin",
    response_model=AIOriginResult,
    summary="Detect AI generation origin of uploaded media",
    description=(
        "Upload an image or video file. This endpoint inspects EXIF/XMP metadata, "
        "filename patterns, pixel-level statistics, and file structure to determine "
        "whether the content was generated by ChatGPT (DALL-E), Gemini Imagen, "
        "Midjourney, Stable Diffusion, Runway ML, or another AI tool."
    ),
)
async def detect_ai_origin(
    file: UploadFile = File(..., description="Image or video file to analyze"),
    media_type: str = Form(default="image", description="'image' or 'video'"),
):
    """
    Detect AI generation origin of an uploaded image or video.

    **Supported formats:**
    - Images: JPEG, PNG, WebP, HEIC, BMP, TIFF
    - Videos: MP4, MOV, WebM, AVI

    **Returns:**
    - `is_ai_generated`: Whether the file appears AI-generated
    - `detected_source`: Which AI tool most likely created it
    - `confidence`: Confidence score (0–1)
    - `detection_signals`: What evidence triggered the detection
    - `summary`: Human-readable verdict
    """
    filename = file.filename or "upload.bin"
    logger.info(f"AI origin check request | filename={filename}")

    # ── Read file ──────────────────────────────────────────────────────────
    try:
        file_bytes = await file.read()
    except Exception as e:
        logger.error(f"File read failed: {e}")
        raise HTTPException(status_code=400, detail="Could not read uploaded file.")

    # ── Size guard ─────────────────────────────────────────────────────────
    if len(file_bytes) > MAX_FILE_SIZE:
        raise HTTPException(
            status_code=413,
            detail=f"File too large. Maximum allowed size is 50 MB (received {len(file_bytes) // (1024*1024)} MB).",
        )

    if len(file_bytes) < 64:
        raise HTTPException(
            status_code=400,
            detail="File is too small to analyze (minimum 64 bytes required).",
        )

    # ── Validate media type ────────────────────────────────────────────────
    if media_type not in ("image", "video"):
        media_type = "image"  # Default fallback

    # ── Run detection ──────────────────────────────────────────────────────
    service = AIOriginService()
    try:
        result = await service.detect(
            filename=filename,
            file_bytes=file_bytes,
            media_type=media_type,
        )
    except Exception as e:
        logger.error(f"AI origin detection failed: {e}")
        raise HTTPException(
            status_code=500,
            detail="An internal error occurred during AI origin analysis.",
        )

    logger.info(
        f"AI origin complete | file={filename} | "
        f"source={result.detected_source.value} | "
        f"confidence={result.confidence:.2%} | ai={result.is_ai_generated}"
    )
    return result
