"""
=============================================================================
SENTINELS OF INTEGRITY — AI Origin Detection Service
Determines whether uploaded media was generated by a specific AI tool
(ChatGPT/DALL-E, Gemini Imagen, Midjourney, Stable Diffusion, etc.)

Detection Approach:
  1. EXIF / XMP Metadata Fingerprinting  — Many AI tools embed metadata
  2. Filename Pattern Matching            — Tools use predictable naming
  3. Pixel-Level Statistical Analysis     — AI images have unique statistical signatures
  4. File Structure Analysis              — AI tools produce characteristic byte patterns
  5. Content Heuristics                   — Known patterns in AI-generated content
=============================================================================
"""

import asyncio
import hashlib
import io
import logging
import math
import os
import re
import struct
from typing import Optional

from app.models.schemas import AIOriginResult, AIOriginSource

logger = logging.getLogger("sentinels.services.ai_origin")


# =============================================================================
# Signature Databases
# =============================================================================

# EXIF / XMP keyword signatures for each tool
AI_METADATA_SIGNATURES: dict[AIOriginSource, list[str]] = {
    AIOriginSource.CHATGPT_DALLE: [
        "openai", "dall-e", "dalle", "gpt4", "chatgpt",
        "openai.com", "DALL-E", "Created with DALL-E",
        "openai dalle", "generate_image",
    ],
    AIOriginSource.GEMINI_IMAGEN: [
        "google", "gemini", "imagen", "bard", "deepmind",
        "google llc", "ai.google", "vertex ai", "imagegeneration",
        "Created by Gemini", "Google Generative AI",
    ],
    AIOriginSource.MIDJOURNEY: [
        "midjourney", "mj", "nijijourney", "niji journey",
        "midjourney.com", "midjourney bot", "discord.gg/midjourney",
        "imagine", "--ar", "--v 5", "--v 6",
    ],
    AIOriginSource.STABLE_DIFFUSION: [
        "stable diffusion", "stablediffusion", "stabilityai",
        "stability ai", "dreamstudio", "automatic1111",
        "sd web ui", "sd-webui", "comfyui", "comfy ui",
        "parameters", "steps:", "sampler:", "cfg scale:",
        "seed:", "model hash:", "denoising strength:",
    ],
    AIOriginSource.RUNWAY_ML: [
        "runway", "runwayml", "runway ml", "gen-2", "gen-3",
        "runway.ml", "runway.com",
    ],
    AIOriginSource.SORA: [
        "sora", "openai sora", "sora model", "openai video",
    ],
    AIOriginSource.ADOBE_FIREFLY: [
        "adobe", "firefly", "adobe firefly", "adobe stock",
        "adobe generative fill", "adobe ai",
    ],
    AIOriginSource.CANVA_AI: [
        "canva", "canva ai", "canva magic", "canva.com",
        "magic media", "magic write",
    ],
    AIOriginSource.BING_IMAGE_CREATOR: [
        "bing", "bing image creator", "bing dalle", "microsoft designer",
        "microsoft", "dall-e 3", "copilot", "designer.microsoft",
    ],
    AIOriginSource.LEONARDO_AI: [
        "leonardo", "leonardo ai", "leonardo.ai", "dreamshaper",
    ],
    AIOriginSource.PIKA_LABS: [
        "pika", "pika labs", "pika.art",
    ],
    AIOriginSource.HEYGEN: [
        "heygen", "heygen.com", "heygen ai",
    ],
    AIOriginSource.SYNTHESIA: [
        "synthesia", "synthesia.io",
    ],
}

# Filename pattern regexes
FILENAME_PATTERNS: dict[AIOriginSource, list[re.Pattern]] = {
    AIOriginSource.CHATGPT_DALLE: [
        re.compile(r'dall.?e', re.I),
        re.compile(r'chatgpt', re.I),
        re.compile(r'openai', re.I),
        re.compile(r'DALL_E_\d{4}', re.I),
        re.compile(r'image_\d{10,}', re.I),   # DALL-E timestamp style
    ],
    AIOriginSource.GEMINI_IMAGEN: [
        re.compile(r'gemini', re.I),
        re.compile(r'imagen', re.I),
        re.compile(r'bard', re.I),
        re.compile(r'google.ai', re.I),
    ],
    AIOriginSource.MIDJOURNEY: [
        re.compile(r'midjourney|mj_\d', re.I),
        re.compile(r'\w+_\w+_\d+_\d+\.png', re.I),  # MJ naming convention
        re.compile(r'\d{19}\.png'),                  # Discord attachment ID
        re.compile(r'niji', re.I),
    ],
    AIOriginSource.STABLE_DIFFUSION: [
        re.compile(r'stable.?diffusion|sd_\d+', re.I),
        re.compile(r'00\d{3}-\d+', re.I),           # A1111 numbering
        re.compile(r'comfy', re.I),
        re.compile(r'dreamshaper|realistic.?vision', re.I),
    ],
    AIOriginSource.RUNWAY_ML: [
        re.compile(r'runway', re.I),
        re.compile(r'gen.?[23]', re.I),
    ],
    AIOriginSource.ADOBE_FIREFLY: [
        re.compile(r'firefly', re.I),
        re.compile(r'adobe.?ai', re.I),
    ],
    AIOriginSource.BING_IMAGE_CREATOR: [
        re.compile(r'bing', re.I),
        re.compile(r'copilot', re.I),
        re.compile(r'designer', re.I),
    ],
    AIOriginSource.LEONARDO_AI: [
        re.compile(r'leonardo', re.I),
        re.compile(r'dreamshaper', re.I),
    ],
    AIOriginSource.PIKA_LABS: [
        re.compile(r'pika', re.I),
    ],
}

# Display-friendly names
SOURCE_DISPLAY_NAMES: dict[AIOriginSource, str] = {
    AIOriginSource.CHATGPT_DALLE:    "ChatGPT",
    AIOriginSource.GEMINI_IMAGEN:    "Gemini",
    AIOriginSource.MIDJOURNEY:       "Midjourney",
    AIOriginSource.STABLE_DIFFUSION: "Stable Diffusion",
    AIOriginSource.RUNWAY_ML:        "Runway",
    AIOriginSource.SORA:             "Sora",
    AIOriginSource.ADOBE_FIREFLY:    "Adobe Firefly",
    AIOriginSource.CANVA_AI:         "Canva",
    AIOriginSource.BING_IMAGE_CREATOR: "Bing Image Creator",
    AIOriginSource.LEONARDO_AI:      "Leonardo",
    AIOriginSource.PIKA_LABS:        "Pika",
    AIOriginSource.HEYGEN:           "HeyGen",
    AIOriginSource.SYNTHESIA:        "Synthesia",
    AIOriginSource.UNKNOWN_AI:       "Unknown AI",
    AIOriginSource.HUMAN_CREATED:    "Human-Created",
}


# =============================================================================
# Core Detection Service
# =============================================================================

class AIOriginService:
    """
    Detects whether uploaded media was generated by a specific AI tool.
    Uses a multi-layer fingerprinting approach.
    """

    async def detect(
        self,
        filename: str,
        file_bytes: bytes,
        media_type: str,
    ) -> AIOriginResult:
        """
        Main entry point. Run all detection layers in parallel.
        
        Args:
            filename:   Original filename of the upload
            file_bytes: Raw bytes of the file
            media_type: 'image' or 'video'
        
        Returns:
            AIOriginResult with source attribution and signals
        """
        logger.info(f"Starting AI origin detection | file={filename} | size={len(file_bytes)}B")

        # Run all detectors concurrently
        metadata_task    = asyncio.create_task(self._analyze_metadata(file_bytes, filename))
        filename_task    = asyncio.create_task(self._analyze_filename(filename))
        pixel_task       = asyncio.create_task(self._analyze_pixel_statistics(file_bytes, media_type))
        structure_task   = asyncio.create_task(self._analyze_file_structure(file_bytes, filename))

        metadata_scores,  metadata_flags  = await metadata_task
        filename_scores,  filename_signals = await filename_task
        pixel_analysis                     = await pixel_task
        structure_scores, structure_flags  = await structure_task

        # Merge scores from all layers
        combined_scores: dict[AIOriginSource, float] = {}
        for source in AIOriginSource:
            score = (
                metadata_scores.get(source, 0.0)  * 0.40  +
                filename_scores.get(source, 0.0)  * 0.25  +
                pixel_analysis.get("scores", {}).get(source, 0.0) * 0.20 +
                structure_scores.get(source, 0.0) * 0.15
            )
            combined_scores[source] = score

        # Find best match
        best_source, best_score = max(
            combined_scores.items(), key=lambda x: x[1]
        )

        # Global AI probability based on non-human score sum
        human_score = combined_scores.get(AIOriginSource.HUMAN_CREATED, 0.0)
        total_ai_score = sum(
            v for k, v in combined_scores.items()
            if k != AIOriginSource.HUMAN_CREATED
        )

        # Normalize confidence
        if best_score < 0.05 or best_source == AIOriginSource.HUMAN_CREATED:
            is_ai = False
            detected = AIOriginSource.HUMAN_CREATED
            confidence = max(0.01, human_score)
        else:
            is_ai = True
            detected = best_source
            confidence = min(0.99, best_score)

        # Secondary sources (sorted by score, excluding primary and human)
        secondary = [
            src for src, sc in sorted(
                combined_scores.items(), key=lambda x: -x[1]
            )
            if src != detected and src != AIOriginSource.HUMAN_CREATED and sc > 0.1
        ][:3]

        # Collect all signals
        all_signals = filename_signals + metadata_flags + structure_flags

        # Build pixel analysis summary (safe to serialize)
        pixel_summary = {
            "uniformity_index":    round(pixel_analysis.get("uniformity_index", 0), 4),
            "noise_signature":     pixel_analysis.get("noise_signature", "unknown"),
            "color_distribution":  pixel_analysis.get("color_distribution", "n/a"),
            "artifact_pattern":    pixel_analysis.get("artifact_pattern", "none"),
        }

        summary = self._build_summary(is_ai, detected, confidence, all_signals)

        result = AIOriginResult(
            is_ai_generated=is_ai,
            confidence=round(confidence, 4),
            detected_source=detected,
            secondary_sources=secondary,
            detection_signals=all_signals[:12],  # Keep top signals
            metadata_flags=metadata_flags[:8],
            pixel_analysis=pixel_summary,
            summary=summary,
        )

        logger.info(
            f"AI Origin Result | source={detected.value} | "
            f"confidence={confidence:.2%} | ai={is_ai}"
        )
        return result

    # -------------------------------------------------------------------------
    # Layer 1: EXIF / XMP / PNG Metadata Analysis
    # -------------------------------------------------------------------------

    async def _analyze_metadata(
        self, file_bytes: bytes, filename: str
    ) -> tuple[dict[AIOriginSource, float], list[str]]:
        """
        Scan EXIF, XMP, PNG tEXt chunks, and JPEG comments for AI signatures.
        """
        scores: dict[AIOriginSource, float] = {}
        flags: list[str] = []

        try:
            # Convert to string (Latin-1 safe for binary scanning)
            raw_text = file_bytes.decode("latin-1", errors="replace").lower()

            for source, keywords in AI_METADATA_SIGNATURES.items():
                for kw in keywords:
                    if kw.lower() in raw_text:
                        scores[source] = scores.get(source, 0.0) + 0.3
                        flags.append(f"Metadata match: '{kw}' → {SOURCE_DISPLAY_NAMES[source]}")
                        break  # One hit per source per keyword group is enough

            # Special: PNG tEXt chunk scanning
            if filename.lower().endswith(".png"):
                chunks = self._extract_png_text_chunks(file_bytes)
                for chunk_key, chunk_val in chunks.items():
                    combined = (chunk_key + chunk_val).lower()
                    flags.append(f"PNG metadata chunk '{chunk_key}': {chunk_val[:80]}")
                    for source, keywords in AI_METADATA_SIGNATURES.items():
                        if any(kw.lower() in combined for kw in keywords):
                            scores[source] = scores.get(source, 0.0) + 0.5
                            flags.append(f"PNG chunk confirms → {SOURCE_DISPLAY_NAMES[source]}")

            # Score as human if no AI metadata detected
            if not scores:
                scores[AIOriginSource.HUMAN_CREATED] = 0.5

        except Exception as e:
            logger.warning(f"Metadata analysis error: {e}")
            scores[AIOriginSource.HUMAN_CREATED] = 0.3

        return scores, flags

    def _extract_png_text_chunks(self, data: bytes) -> dict[str, str]:
        """Parse PNG tEXt and iTXt chunks."""
        result = {}
        try:
            if data[:8] != b"\x89PNG\r\n\x1a\n":
                return result
            pos = 8
            while pos < len(data) - 12:
                length = struct.unpack(">I", data[pos:pos+4])[0]
                chunk_type = data[pos+4:pos+8].decode("ascii", errors="replace")
                chunk_data = data[pos+8:pos+8+length]
                pos += 12 + length
                if chunk_type in ("tEXt", "iTXt"):
                    try:
                        null_pos = chunk_data.index(b"\x00")
                        key = chunk_data[:null_pos].decode("utf-8", errors="replace")
                        val = chunk_data[null_pos+1:].decode("utf-8", errors="replace")
                        result[key] = val
                    except Exception:
                        pass
        except Exception:
            pass
        return result

    # -------------------------------------------------------------------------
    # Layer 2: Filename Pattern Analysis
    # -------------------------------------------------------------------------

    async def _analyze_filename(
        self, filename: str
    ) -> tuple[dict[AIOriginSource, float], list[str]]:
        """Check filename against known AI tool naming conventions."""
        scores: dict[AIOriginSource, float] = {}
        signals: list[str] = []

        for source, patterns in FILENAME_PATTERNS.items():
            for pattern in patterns:
                if pattern.search(filename):
                    scores[source] = scores.get(source, 0.0) + 0.4
                    signals.append(
                        f"Filename pattern '{pattern.pattern}' matches → {SOURCE_DISPLAY_NAMES[source]}"
                    )
                    break

        # Generic AI-tool suffixes
        generic_ai_suffixes = [
            ("ai_generated", AIOriginSource.UNKNOWN_AI, "Generic AI filename suffix"),
            ("ai generated", AIOriginSource.UNKNOWN_AI, "Generic AI filename token"),
            ("generated_by", AIOriginSource.UNKNOWN_AI, "'generated_by' in filename"),
            ("prompt_", AIOriginSource.UNKNOWN_AI, "Prompt-style filename"),
        ]
        for token, source, desc in generic_ai_suffixes:
            if token in filename.lower():
                scores[source] = scores.get(source, 0.0) + 0.3
                signals.append(desc)

        return scores, signals

    # -------------------------------------------------------------------------
    # Layer 3: Pixel-Level Statistical Analysis
    # -------------------------------------------------------------------------

    async def _analyze_pixel_statistics(
        self, file_bytes: bytes, media_type: str
    ) -> dict:
        """
        Perform pixel-level statistical analysis using byte distribution.
        
        Real camera photos have specific noise patterns, DCT coefficient distributions,
        and color histograms. AI-generated images tend to have:
        - Higher color uniformity in large regions
        - Unnaturally smooth gradients
        - Specific frequency domain signatures
        - Missing PRNU (Photo Response Non-Uniformity) noise
        """
        result = {
            "uniformity_index": 0.0,
            "noise_signature": "unknown",
            "color_distribution": "n/a",
            "artifact_pattern": "none",
            "scores": {},
        }

        try:
            # Sample bytes for statistics (use first ~50KB as approximation)
            sample = file_bytes[:51200] if len(file_bytes) > 51200 else file_bytes
            byte_array = bytearray(sample)

            if not byte_array:
                return result

            # ── Byte frequency distribution (entropy analysis) ──────────────
            freq = [0] * 256
            for b in byte_array:
                freq[b] += 1

            n = len(byte_array)
            entropy = 0.0
            for count in freq:
                if count > 0:
                    p = count / n
                    entropy -= p * math.log2(p)

            # AI images often have entropy around 7.2–7.8 (not max 8.0 like noise, not low like blank)
            ai_entropy_score = 1.0 - abs(entropy - 7.5) / 2.0
            ai_entropy_score = max(0.0, min(1.0, ai_entropy_score))

            # ── Uniformity: check for long runs of similar bytes ────────────
            # AI images tend to have smoother regions → more byte runs
            runs = 0
            prev_byte = byte_array[0]
            run_len = 1
            for b in byte_array[1:]:
                if abs(b - prev_byte) <= 2:
                    run_len += 1
                else:
                    if run_len > 4:
                        runs += run_len
                    run_len = 1
                prev_byte = b
            uniformity_index = min(1.0, runs / max(n, 1))

            # ── Peak detection in frequency domain (approximate DCT via byte variance) ──
            block_variances = []
            block_size = 64
            for i in range(0, min(n, 8192), block_size):
                block = byte_array[i:i+block_size]
                if len(block) < 8:
                    continue
                mean = sum(block) // len(block)
                variance = sum((b - mean) ** 2 for b in block) / len(block)
                block_variances.append(variance)

            # AI images have lower average local variance (smoother areas)
            avg_variance = sum(block_variances) / len(block_variances) if block_variances else 128
            # Normalize: real cameras produce higher variance (noise / detail)
            smoothness_score = 1.0 - min(1.0, avg_variance / 3000.0)

            # ── Combine for overall AI probability ──────────────────────────
            ai_pixel_prob = (ai_entropy_score * 0.4 + uniformity_index * 0.3 + smoothness_score * 0.3)

            result["uniformity_index"] = uniformity_index
            result["noise_signature"] = (
                "low-noise (AI-like)" if smoothness_score > 0.6
                else "natural camera noise"
            )
            result["color_distribution"] = (
                "uniform (AI-typical)" if uniformity_index > 0.5
                else "natural distribution"
            )
            result["artifact_pattern"] = (
                "smooth gradients" if smoothness_score > 0.7
                else "organic texture"
            )

            # Assign pixel-level AI probability
            if ai_pixel_prob > 0.55:
                result["scores"][AIOriginSource.UNKNOWN_AI] = ai_pixel_prob * 0.5

        except Exception as e:
            logger.warning(f"Pixel analysis error: {e}")

        return result

    # -------------------------------------------------------------------------
    # Layer 4: File Structure / Magic Bytes Analysis
    # -------------------------------------------------------------------------

    async def _analyze_file_structure(
        self, file_bytes: bytes, filename: str
    ) -> tuple[dict[AIOriginSource, float], list[str]]:
        """
        Analyze file structure for AI tool signatures embedded in containers.
        
        - JPEG comment segments (APP0/APP1/COM markers)
        - PNG iTXt with AI parameters
        - MP4/WebM metadata atoms
        - Specific file size signatures
        """
        scores: dict[AIOriginSource, float] = {}
        flags: list[str] = []
        ext = os.path.splitext(filename)[1].lower()

        try:
            # ── JPEG structural analysis ──────────────────────────────────
            if ext in (".jpg", ".jpeg") and len(file_bytes) > 4:
                if file_bytes[:2] == b"\xff\xd8":
                    flags.append("Valid JPEG structure detected")
                    # Scan APP markers for AI tool signatures
                    comments = self._extract_jpeg_comments(file_bytes)
                    for comment in comments:
                        c_lower = comment.lower()
                        for source, keywords in AI_METADATA_SIGNATURES.items():
                            if any(kw.lower() in c_lower for kw in keywords):
                                scores[source] = scores.get(source, 0.0) + 0.6
                                flags.append(f"JPEG comment contains AI signature → {SOURCE_DISPLAY_NAMES[source]}")

                    # DALL-E produced JPEGs often have specific size signatures
                    size = len(file_bytes)
                    if 200_000 < size < 500_000:
                        # DALL-E 3 standard size range
                        scores[AIOriginSource.CHATGPT_DALLE] = (
                            scores.get(AIOriginSource.CHATGPT_DALLE, 0.0) + 0.1
                        )

            # ── PNG structural analysis ───────────────────────────────────
            elif ext == ".png":
                chunks = self._extract_png_text_chunks(file_bytes)
                if "parameters" in chunks or "Parameters" in chunks:
                    # Stable Diffusion web UI embeds "parameters" chunk
                    scores[AIOriginSource.STABLE_DIFFUSION] = (
                        scores.get(AIOriginSource.STABLE_DIFFUSION, 0.0) + 0.8
                    )
                    flags.append("PNG 'parameters' metadata chunk found — Stable Diffusion signature")

                if "Comment" in chunks:
                    comment_val = chunks["Comment"].lower()
                    if "midjourney" in comment_val:
                        scores[AIOriginSource.MIDJOURNEY] = scores.get(AIOriginSource.MIDJOURNEY, 0.0) + 0.8
                        flags.append("PNG Comment confirms Midjourney origin")

            # ── Video structural analysis (MP4/MOV) ───────────────────────
            elif ext in (".mp4", ".mov", ".webm"):
                sample = file_bytes[:4096].decode("latin-1", errors="replace").lower()
                video_ai_sigs = {
                    "runway": AIOriginSource.RUNWAY_ML,
                    "sora": AIOriginSource.SORA,
                    "pika": AIOriginSource.PIKA_LABS,
                    "heygen": AIOriginSource.HEYGEN,
                    "synthesia": AIOriginSource.SYNTHESIA,
                    "gen-2": AIOriginSource.RUNWAY_ML,
                    "gen-3": AIOriginSource.RUNWAY_ML,
                }
                for sig, source in video_ai_sigs.items():
                    if sig in sample:
                        scores[source] = scores.get(source, 0.0) + 0.7
                        flags.append(f"Video container signature '{sig}' → {SOURCE_DISPLAY_NAMES[source]}")

            # ── Generic: scan first 4KB for any AI fingerprint ────────────
            header_text = file_bytes[:4096].decode("latin-1", errors="replace").lower()
            for source, keywords in AI_METADATA_SIGNATURES.items():
                for kw in keywords:
                    if kw.lower() in header_text:
                        scores[source] = scores.get(source, 0.0) + 0.2
                        flags.append(f"File header contains '{kw}'")
                        break

        except Exception as e:
            logger.warning(f"Structure analysis error: {e}")

        return scores, flags

    def _extract_jpeg_comments(self, data: bytes) -> list[str]:
        """Parse JPEG APP0-APP15 and COM segments for text."""
        comments = []
        try:
            i = 2  # Skip SOI marker
            while i < len(data) - 4:
                if data[i] != 0xFF:
                    break
                marker = data[i+1]
                # APP markers (E0-EF) and COM (FE)
                if (0xE0 <= marker <= 0xEF) or marker == 0xFE:
                    seg_len = struct.unpack(">H", data[i+2:i+4])[0]
                    seg_data = data[i+4:i+2+seg_len]
                    try:
                        text = seg_data.decode("utf-8", errors="replace")
                        if text.strip():
                            comments.append(text)
                    except Exception:
                        pass
                    i += 2 + seg_len
                elif marker in (0xD8, 0xD9):
                    i += 2
                else:
                    if i + 4 > len(data):
                        break
                    try:
                        seg_len = struct.unpack(">H", data[i+2:i+4])[0]
                        i += 2 + seg_len
                    except Exception:
                        break
        except Exception:
            pass
        return comments

    # -------------------------------------------------------------------------
    # Summary Builder
    # -------------------------------------------------------------------------

    def _build_summary(
        self,
        is_ai: bool,
        source: AIOriginSource,
        confidence: float,
        signals: list[str],
    ) -> str:
        name = SOURCE_DISPLAY_NAMES.get(source, source.value)
        pct = round(confidence * 100)

        if not is_ai:
            return (
                f"✅ Content appears to be human-created or captured by a real camera. "
                f"No AI generation signatures were detected across metadata, filename, "
                f"pixel statistics, and file structure analysis."
            )

        signal_summary = ""
        if signals:
            signal_summary = f" Key indicators: {'; '.join(signals[:3])}."

        return (
            f"⚠️ AI-GENERATED CONTENT DETECTED with {pct}% confidence. "
            f"Most likely generated by: {name}.{signal_summary} "
            f"This media does not appear to be captured by a real-world camera or device."
        )
